### ISSUE TITLE
cannot import numpy

### ISSUE THREAD

**Issue by Asiyeh-Bahaloo** [maierbn/opendihu#2]
Thank you for this open source framework.
I want to simulate orbicularis oculi muscle contraction which closes the eyelid, but i couldn't install opendihu.
first, i tried the instructions provided [here](https://opendihu.readthedocs.io/en/latest/user/installation.html) which lead to an error more or less like:
`scons only work with python2`

then i figured out that, python version in the make file should be python2 so i changed this line
`python := python3`
to
`python := /usr/bin/python`

but now python interpreter doesn't know numpy (and i guess other libraries). since opendihu sets up a python env for itself in `opendihu/dependencies/python/install` and probably it is expected to be the python version that opendihu uses in this step, i checked installed libraries for that environment and found all dependencies installed and working. 
then I checked the system default `/usr/bin/python` after make command and found that symlink  was changed to python2.7 by make! Here is how my config.log looks like:

[config.log](https://github.com/maierbn/opendihu/files/5531285/config.log)

**Comment by maierbn** [comment]
Hi,
sorry for the late reply, I didn't check github issues before. If you're still interested in getting it installed, maybe you could try again with the latest version or release. Now everything including the packaged `scons` should work with python3. 

The problem with `numpy` not being found can usually be fixed by manually installing it (and the other packages) in the environment: 
```
opendihu/dependencies/python/install/bin/python3 -m pip install numpy matplotlib scipy numpy-stl svg.path triangle geomdl
```
However, this should have already been done by scons. It can be triggered again with `scons PYTHONPACKAGES_REBUILD=True`.
