### ISSUE TITLE
Mapping between FastMonodomainSolver and MuscleContractionSolver

### ISSUE THREAD

**Issue by carme-hp** [maierbn/opendihu#21]
# Setup:
I consider a single cuboid muscle with dimensions 3x3x14.8 cm and 4x4 fibers. Each fiber covers the whole length of the muscle(14.8cm) and has 40 points. The fibers are activated in a symmetric fashion using an input file. At z=0, the muscle is fixed to the wall, while at the other end no boundary condition is specified.

We investigate what happens when the spatial resolution of the 3D continuum mechanics solver is changed, eg. [mx,my,mz]

# Observations

![Figure_1](https://user-images.githubusercontent.com/71499004/235648748-758124c7-3ee5-45b4-9648-20fd2c98f1ab.png)

The resulting contraction of the muscle seems to be dependent on the spatial resolution of the mechanics solver. However in #20  we saw that when the mechanics solver alone is used, the results don't vary with the spatial resolution. Therefore, **I suspect of a mapping issue between fibers and the mechanics' 3D mesh.**

The quantity that is being map from the fibers to the 3D mesh is the activation parameter (gamma). OpenDiHu uses consistent mapping, and thus it is expected that the activation parameter changes with the resolution. This is what we see in the next plots:

![Figure_2](https://user-images.githubusercontent.com/71499004/235650725-6f42e657-947c-47c0-91b1-c546bb0fb5e5.png)

![Figure_3](https://user-images.githubusercontent.com/71499004/235649541-475d9c81-9451-4094-8382-0ad412dd6360.png)

**But is it actually correct to use consistent mapping? Shouldn't we use conservative mapping?**

Overall, **the stress should not depend on the spatial resolution**. Yet, if we plot the total active stress `activePK2StressVariable` we see how it is clearly not:
![Figure_3](https://user-images.githubusercontent.com/71499004/235650626-d794540e-b41f-404f-8007-e2d7ef036245.png)
![Figure_4](https://user-images.githubusercontent.com/71499004/235650629-a1159cbf-252b-4ee4-94e5-81c549d33893.png)

Note that the stress has 3x3 components. We only plot the zz coordinate, which should be the most important one and the xx coordinate. That the xx coordinate adds up to 0 makes sense as the muscle is contracting in the z direction.

**Comment by maierbn** [comment]
* Can you repeat this study with a finer 1D mesh, e.g. 1480 elements instead of 40?
* Can you conduct another study with constant 3D resolution and varying number of 1D mesh elements?

* You probably have read how the mapping within opendihu is implemented (in the [docu](https://opendihu.readthedocs.io/en/latest/settings/mappings_between_meshes.html#mapping) or in more detail in chapter 7.8 of the book, 7.8.2 seems relevant). A motivation why it was done the way it is was to make it efficient/even possible with the domain decomposition. Maybe can we understand the exact behavior in our special case of a coarse 1D mesh (fiber) and a fine 1D mesh (subset of solid mechanics mesh)? I remember I did pencil drawings for this case and wrote down the resulting equations, maybe you can try it also.
* If it turns out this is a problem, can you try to replace the mapping by a precice mapping? E.g. RBF mapping with two participants, fibers and mechanics.

**Comment by carme-hp** [comment]
Thanks a lot for the input @maierbn , however it seems the issue was due to how I selected the connecting slots and is fix by this [commit](https://github.com/maierbn/opendihu/commit/f4a166590fb192de5dd97ddaee70660e524af779) :
![after](https://user-images.githubusercontent.com/71499004/236325607-e1119b12-d0b2-4502-be9b-3750bafb612a.png)

Before we had:
![before](https://user-images.githubusercontent.com/71499004/236325505-f4188275-955c-4370-ae70-4cb95515f3ea.png)

>>**Warning**
> The previous slot configuration was copied from FH's `two_muscles_with_tendon` example. It's yet to be checked if there it was working properly.

With this changes the spatial resolution study looks much better:

![Figure_1](https://user-images.githubusercontent.com/71499004/236325798-9712080c-0789-4362-9d2c-418537f4ff0d.png)
Note that the fact that case 4 is a layout can be explained by the fact the fiber mesh has a coarser resolution in x,y  than the mechanics solver (eg. #20 )

Given the results, consistent mapping doesn't seem to be an issue:
![Figure_3](https://user-images.githubusercontent.com/71499004/236325815-7303dbb3-6fdd-416b-a060-59f6235b45a5.png)
This plots compares the new computed values of stress (dashed lines) vs the previous ones. We see that the stress varies with the resolution.

**Comment by ghoshgm** [comment]
Probably, we can answer the question, 'When the mechanics mesh is finer than the fiber mesh, which nodes of the fiber mesh contribute to the elements of the mechanics mesh ?' by adopting the basic idea used by the RBF mapping in preCICE. We may not necessarily need RBF because at the end of the day it is just a interpolation scheme which can be used to compute the weighted sum of the approximation polynomial. There is a catalog of interpolation schemes, we only care about computing the approximation polynomial.

As per this paper,
https://arxiv.org/abs/2109.14470

The RBF mapping creates a global interpolation function for the source mesh and the target mesh can directly sample values from that function. Unlike, nearest neighbor/nearest projection I think RBF mapping does not depend on mesh connectivity to find contributing vertices because the paper makes no mention about it. I can fact-check with David next week.

My proposition is that we create global interpolation functions for both mechanics mesh and fiber mesh using a interpolation scheme (lagrange or RBF) and then with a few co-ordinate scaling operations we can directly sample values without worrying about which fiber nodes to consider for mechanics mesh elements. This should work both ways.

I skipped a few details to make it easier to understand. Naturally, this is open for discussion.

**Comment by maierbn** [comment]
My thought is that you arrive at a converged solution only by refining all participating discretizations at the same time. The coarse 1D mesh is maybe questionable.
Anyhow, investigation with RBF based mapping is a good idea. Questions can be
* convergence of mechanics solution with varying 3D mesh
* reasonable relation of 1D/3D mesh sizes "which nodes contribute how much"
* runtime comparison to opendihu-internal local mapping in parallel setting 

From a physiological pov, often AP propagation velocities are important therefore the 1D problems should favorably have low error.

**Comment by ghoshgm** [comment]
The RBF mapping looks tempting but I am not fully sure if the preCICE implementation works for meshes with different dimensions. This needs to be fact-checked with the preCICE team.

**Comment by carme-hp** [comment]
Precice can handle meshes with different dimensionality. Note that  we use opendihu's precice volume adapter to map from the fibers to the mechanics mesh using rbf interpolation.

**Comment by maierbn** [comment]
OpenDiHu moves to its [new home](https://github.com/opendihu/opendihu) under its own Github Organization :house:. The current repo will be archived soon.

Therefore all issues in the old repo must be closed now, sorry. But you can reopen your issue in the new repo where it will get new attention. :rocket:
