### ISSUE TITLE
Use FastMonodomainSolver as a Controlling Solver

### ISSUE THREAD

**Issue by erikscheurer** [maierbn/opendihu#6]
In a setup, where the `FastMonodomainSolver` is the the main controlling solver of the simulation, the entire Simulation only iterates one timestep. This assumes a setup of type:
```c++
int main(int argc, char *argv[])
{

  DihuContext settings(argc, argv);
  FastMonodomainSolver<
	      Control::MultipleInstances<                       // or something similar
		....
  > problem(settings);
...
}

```

This is due to the fact, that [in the `FastMonodomainSolver`](https://github.com/maierbn/opendihu/blob/c5b98714af349ff1ca90d8cee1fafc64386fb860/core/src/specialized_solver/fast_monodomain_solver/fast_monodomain_solver_compute.tpp#L10-L11) `advanceTimeSpan()` is only called once. Thereby, changing the `endtime` to anything other than the time step width results in only one step being simulated. 

Is this intended behavior? Is the time supposed to be set in a nested solver? This did also not work for me in a [modified example](https://github.com/maierbn/opendihu/blob/c5b98714af349ff1ca90d8cee1fafc64386fb860/examples/electrophysiology/neuromuscular/singlefiber/settings_monodomain.py#L306-L307). As described before, using the [`FastMonodomainSolver`](https://github.com/maierbn/opendihu/blob/c5b98714af349ff1ca90d8cee1fafc64386fb860/examples/electrophysiology/neuromuscular/singlefiber/src/MonodomainSolver.cpp#L45) as the main control unit, only one time step of size [dt=1e-2](https://github.com/maierbn/opendihu/blob/c5b98714af349ff1ca90d8cee1fafc64386fb860/examples/electrophysiology/neuromuscular/singlefiber/settings_monodomain.py#L303) is executed and the simulation ends afterwards.
If not intended, is it possible to extend the functionality of the `FastMonodomainSolver` to iterate multiple steps, without breaking existing functionality?

This problem means also, that the Outputwriter is only called once in this time step.

**Comment by carme-hp** [comment]
I think this is not correct.  Yes, the function `advanceTimeSpan()` is only called once, and since this is the function where the *OutputWriter* is called, we only get a single output file. However `end_time` does play a role and the number of steps we simulate is defined by it (check terminal output with [this settings](https://github.com/maierbn/opendihu/blob/debug-fibers/examples/electrophysiology/fibers/cuboid_fast_monodomain/settings_fastmonodomain.py)). 

I think that the time for-loop of the FastMonodomainSolver takes place in the function [`computeMonodomain()`](https://github.com/maierbn/opendihu/blob/debug-fibers/core/src/specialized_solver/fast_monodomain_solver/fast_monodomain_solver_compute.tpp), which is called in `advanceTimeSpan()` .

The question is not how to get the [FastMonodomainSolver](https://github.com/maierbn/opendihu/blob/debug-fibers/examples/electrophysiology/fibers/cuboid_fast_monodomain/src/fastmonodomain.cpp) to iterate multiple steps, but how to call the *OuputWriter* at each step, without destroying existing functionality, eg [when we use FastMonodomainSolver as part of a coupling scheme](https://github.com/maierbn/opendihu/blob/debug-fibers/examples/electrophysiology/fibers/cuboid_fast_monodomain/src/coupled_fastmonodomain.cpp).

**Comment by carme-hp** [comment]
I have a possible solution to the problem, see #7
